<?php

namespace Eccube\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CustomerSupporterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CustomerSupporterRepository extends EntityRepository
{
}
