<?php

namespace Eccube\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CustomerBasicInfoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CustomerBasicInfoRepository extends EntityRepository
{
	public function getCustomerBasicInfoByCustomer(\Eccube\Entity\Customer $Customer)
	{
		return $this->createQueryBuilder('c')
    			->where('c.Customer = :Customer')
    			->setParameter('Customer', $Customer)
    			->getQuery()
    			->getOneOrNullResult();
	}

	public function getCustomerBasicInfoByExemption(\Eccube\Entity\Master\ExemptionType $ExemptionType)
	{

		return $this->createQueryBuilder("c")
				->where("c.ExemptionType = :ExemptionType")
				->setParameter('ExemptionType', $ExemptionType)
				->getQuery()
				->getResult();
	}
}
