<?php

namespace Eccube\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CustomerQrRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CustomerQrRepository extends EntityRepository
{
}
