<?php

namespace Eccube\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MembershipBillingStatusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MembershipBillingStatusRepository extends EntityRepository
{
	public function getBillingStatus($Customer = null)
    {
    	return $this->createQueryBuilder('h')
    			->where('h.Customer = :Customer')
    			->orderBy('h.ProductMembership')
    			->setParameter('Customer', $Customer)
    			->getQuery()
    			->getResult();
    }
}
