<?php

namespace Eccube\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ProductMembershipRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductMembershipRepository extends EntityRepository
{
    /**
     * @var \Eccube\Application
     */
    protected $app;

    public function setApplication(Application $app)
    {
        $this->app = $app;
    }

    /**
     * ”N‰ï”ïˆê——‚ğæ“¾‚·‚é.
     *
     * @return \Eccube\Entity\ProductMembership[] ”N‰ï”ï‚Ì”z—ñ
     */
    public function getList(Category $Parent = null, $flat = false)
    {
        $options = $this->app['config']['doctrine_cache'];
        $lifetime = $options['result_cache']['lifetime'];

        $qb = $this->createQueryBuilder('pm')
            ->select('pm')
            ->orderBy('pm.membership_year', 'DESC');
        $ProductMembership = $qb->getQuery()
            ->useResultCache(true, $lifetime)
            ->getResult();

        return $ProductMembership;
    }


    /**
     * ”N‰ï”ï“o˜^—L–³‚ğæ“¾‚·‚é.
     *
     * @return ”N‰ï”ï“o˜^—L–³
     */
    public function isExistsMembership($membershipYear, $exclusionProductId = false)
    {
        $qb = $this->createQueryBuilder('pm')
            ->leftJoin('pm.Product', 'p')
            ->select('pm')
            ->where('pm.membership_year = :membership_year')
            ->setParameters(array(
                'membership_year' => $membershipYear
            ))
            ->orderBy('pm.membership_year', 'DESC');
        if (!is_null($exclusionProductId)) {
            $qb
                ->andWhere('p.id <> :product_id')
                ->setParameter('product_id', $exclusionProductId);
        }
        $ProductMembership = $qb->getQuery()
            ->getResult();
        return (0 < count($ProductMembership));
    }
}
