<?php

namespace Eccube\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ProductDataRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductDataRepository extends EntityRepository
{
}
