<?php

namespace Plugin\ProductVideo\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ProductVideoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductVideoRepository extends EntityRepository
{
}
