<?php

namespace Eccube\Repository\Master;

use Doctrine\ORM\EntityRepository;

/**
 * CustomerBasicInfoStatusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CustomerBasicInfoStatusRepository extends EntityRepository
{
}
